import type { IdviaEnvironment, IdviaUrls } from './environments';
export interface IdviaUseCaseIds {
    videoIdUnassisted?: string;
    videoIdAssisted?: string;
    sign?: string;
}
export interface IdviaClientConfig {
    environment: IdviaEnvironment;
    clientId: string;
    clientSecret: string;
    useCaseIds?: IdviaUseCaseIds;
    /** Escape hatch overriding the environment presets. */
    urls?: Partial<IdviaUrls>;
}
/**
 * The API's nested `configuration` object — mandatory on the create call.
 * Landing URLs, expiry and all verification tuning live here, not top-level.
 */
export interface VideoIdUnassistedConfiguration {
    saveVideoRecording?: boolean;
    /** Language code: 'EN', 'ES', 'FR', … */
    language?: string;
    landingURL?: string;
    landingKoUrl?: string;
    otpBefore?: boolean;
    otpDuring?: boolean;
    preCallTest?: boolean;
    checkMrz?: boolean;
    manualSnapshot?: boolean;
    useDocumentVerificationEngine?: boolean;
    usePassiveLifeLivenessEngine?: boolean;
    passiveLifeLivenessThreshold?: number;
    checkForFaceMatching?: boolean;
    faceMatchSimilarityThreshold?: number;
    useActiveLifeLivenessEngine?: boolean;
    slaExpirationSeconds?: number;
    slaExpirationAdviseSeconds?: number;
    videoAssistedInterconnection?: boolean;
    workflow?: string[];
    [key: string]: unknown;
}
/** Documented fields are typed; the index signature passes further top-level fields (name, surname, …) through. */
export interface CreateVideoIdUnassistedParams {
    useCaseId?: string;
    clientReference: string;
    /** Document type the user will present — mandatory in the API: 'Id', 'Passport', 'DrivingLicense', 'ResidencePermit', … */
    docType: string;
    /** Document number — mandatory AND non-empty in the API (400 "'DocNumber' is Required" otherwise). */
    docNumber: string;
    /** Mapped into configuration.landingURL. */
    landingUrl: string;
    /** Mapped into configuration.landingKoUrl. */
    landingKoUrl?: string;
    /** Extra configuration entries; landingUrl/landingKoUrl params take precedence over duplicates here. */
    configuration?: VideoIdUnassistedConfiguration;
    [key: string]: unknown;
}
export interface CreateVideoIdAssistedParams {
    useCaseId?: string;
    clientReference: string;
    /** ISO 3166-1 alpha-2 country code where the service is provided — mandatory in the API. */
    serviceCountry: string;
    /** ISO 639-1 alpha-2 language code — mandatory in the API. */
    language: string;
    /** Subject's first name — some use cases reject the call without it. */
    name?: string;
    /** Subject's surname(s) — some use cases reject the call without it. */
    surname?: string;
    /**
     * Document type — mandatory in the API (400 "Document type is Required" otherwise).
     * Accepted values: 'Id', 'Passport', 'DrivingLicense', 'MilitaryId', 'ResidencePermit', 'IdCard', 'NC', 'PP', 'DL', 'RP'.
     */
    docType: string;
    /** Document number — mandatory and non-empty in the API (400 "Document number is Required" otherwise). */
    docNumber: string;
    landingUrl: string;
    [key: string]: unknown;
}
export interface CreateVideoIdResult {
    url: string;
    trustCloudFileId: string;
    videoIdentificationId: string;
}
/** Assisted deployments may return only the URL (plain-text response) — the ids are then absent. */
export interface CreateVideoIdAssistedResult {
    url: string;
    trustCloudFileId?: string;
    videoIdentificationId?: string;
}
/**
 * Signer shape per the Sign API; passthrough for undocumented fields.
 *
 * For an EMBEDDED signing URL (the one this SDK renders) the API needs, per signer:
 * `id` (a UUID you generate, referenced from `signatures[].identityId`), `order`,
 * `role: 'SIGNER'`, `signMode: 'EMBEBED'` (sic) and `authenticationMethod` (e.g. 'NONE').
 * Without `signMode: 'EMBEBED'` the create call succeeds but no embedded URL is ever produced.
 */
export interface SignSigner {
    /** The signer's reference — also what getSignUrl's identityClientReference path segment expects. */
    clientReference?: string;
    name?: string;
    lastName?: string;
    documentNumber?: string;
    email?: string;
    mobile?: string;
    /** UUID generated by the caller; `signatures[].identityId` points at it. */
    id?: string;
    order?: number;
    role?: 'SIGNER' | string;
    /** 'EMBEBED' (API spelling) for an in-app ceremony; other modes send the signer a link instead. */
    signMode?: 'EMBEBED' | string;
    /** 'NONE', or the second factor the ceremony must enforce. */
    authenticationMethod?: 'NONE' | string;
    [key: string]: unknown;
}
export interface SignDocument {
    /** UUID generated by the caller; `signatures[].documentId` points at it. */
    id?: string;
    url?: string;
    base64?: string;
    documentReference?: string;
    fileName?: string;
    [key: string]: unknown;
}
/** Where a signature goes on a document: at a text anchor and/or at x/y (points) on a page. */
export interface SignPosition {
    anchor?: string;
    pageNumber?: number | null;
    x?: number;
    y?: number;
    [key: string]: unknown;
}
/** Links one signer to one document. The API needs at least one entry to produce a signing ceremony. */
export interface SignSignature {
    /** `SignDocument.id` */
    documentId: string;
    /** `SignSigner.id` */
    identityId: string;
    positions: SignPosition[];
    type?: 'SIGNER' | string;
    [key: string]: unknown;
}
export interface SignReminders {
    expireAfter?: number;
    expireWarn?: number;
    reminderDelay?: number;
    reminderFrequency?: number;
    [key: string]: unknown;
}
/**
 * Body of the Sign create call. The minimal shape (signers + documents) is accepted by the
 * API but is NOT enough for an embedded ceremony — see `SignSigner` and `signatures`.
 */
export interface CreateSignParams {
    useCaseId?: string;
    clientReference?: string;
    signers: SignSigner[];
    documents: SignDocument[];
    /** Signer ↔ document links with positions. Required for the provider to build the ceremony. */
    signatures?: SignSignature[];
    /** Close the envelope automatically once every signer has signed. */
    autoClose?: boolean;
    reminders?: SignReminders;
    [key: string]: unknown;
}
export interface CreateSignResult {
    trustCloudFileId: string;
}
export interface GetSignUrlParams {
    useCaseId?: string;
    trustCloudFileId: string;
    identityClientReference: string;
}
export interface CreateSignSessionParams extends CreateSignParams {
    /** Which signer's URL to fetch. Defaults to the first signer. */
    identityClientReference?: string;
    /**
     * The embedded URL is produced asynchronously after the create call; the API answers
     * 400 "No url found for operation" until then (5-20 s observed). How many times to poll
     * getSignUrl before giving up. Default 15.
     */
    urlRetries?: number;
    /** Delay between polls, in milliseconds. Default 3000. */
    urlRetryDelayMs?: number;
}
export interface CreateSignSessionResult {
    url: string;
    trustCloudFileId: string;
}
export interface VideoIdUnassistedStatusParams {
    useCaseId?: string;
    trustCloudFileId: string;
    videoIdentificationId: string;
}
export interface VideoIdAssistedStatusParams {
    useCaseId?: string;
    trustCloudFileId: string;
}
export interface SignStatusParams {
    useCaseId?: string;
    trustCloudFileId: string;
}
export interface SignStatusResult {
    status: 'Completed' | 'Pending' | 'Cancelled' | string;
    [key: string]: unknown;
}
//# sourceMappingURL=types.d.ts.map